server:
  port: 8888
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      max-idle: 15
      min-idle: 5
      max-active: 30
      max-wait: 500
    aop:
      proxy-target-class: true
      auto: true
