server:
  port: 8888
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    pool:
      max-idle: 15
      min-idle: 5
      max-active: 30
      max-wait: 500
    aop:
      proxy-target-class: true
      auto: true
scheduled:
#  cron: 0/5 * * * * ?
# Spring Boot 2.1 以上可以通过将corn配置为-关闭自动任务
  cron: "-"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    driver: com.mysql.jdbc.Driver
